{% set version = "1.9.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-wcorr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/wCorr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/wCorr/wCorr_{{ version }}.tar.gz
  sha256: 760f7d4ce738e14e4f3fa76ead8615c4042c730110e85d7ed075b0ea8bceb682

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-minqa
    - r-mnormt
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-rcpparmadillo
    - r-minqa
    - r-mnormt

test:
  commands:
    - $R -e "library('wCorr')"           # [not win]
    - "\"%R%\" -e \"library('wCorr')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=wCorr
  license: GPL-2.0-only
  summary: Calculates Pearson, Spearman, polychoric, and polyserial correlation coefficients, in weighted or unweighted form. The package implements tetrachoric correlation as a special case of the polychoric and biserial correlation as a specific case of the polyserial.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - khusmann

# Package: wCorr
# Type: Package
# Title: Weighted Correlations
# Version: 1.9.1
# Date: 2017-05-17
# Author: Ahmad Emad & Paul Bailey
# Maintainer: Paul Bailey <pbailey@air.org>
# Description: Calculates Pearson, Spearman, polychoric, and polyserial correlation coefficients, in weighted or unweighted form. The package implements tetrachoric correlation as a special case of the polychoric and biserial correlation as a specific case of the polyserial.
# License: GPL-2
# BugReports: https://github.com/ahmademad/wCorr/issues
# Imports: minqa, mnormt, Rcpp, stats
# Depends: R (>= 3.1.0)
# RoxygenNote: 6.0.1
# Suggests: knitr, rmarkdown, lattice, captioner
# VignetteBuilder: knitr
# LinkingTo: Rcpp, RcppArmadillo
# NeedsCompilation: yes
# Packaged: 2017-05-17 14:03:39 UTC; pdbailey
# Repository: CRAN
# Date/Publication: 2017-05-18 03:44:58 UTC
